version: '3'
services:
  db:
    container_name: app_database
    build: ./database-docker
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - './database:/var/lib/mysql'
    networks:
      - 'app-network'
  app:
    container_name: app
    build: ./app-docker
    working_dir: '/app'
    command: '/bin/bash -c "echo 5秒後に起動します。 && sleep 5 && ruby App.rb -o 0.0.0.0"'
    volumes:
      - './app:/app'
    ports:
      - '80:4567'
    depends_on:
      - 'db'
    networks:
      - 'app-network'
networks:
  app-network:
    driver: 'bridge'
